// This file was autogenerated by closure/bin/build/depswriter.py.
// Please do not edit.
goog.addDependency('../../app/gtug/base.js', ['Gtug', 'Gtug.Base'], []);
goog.addDependency('../../app/gtug/gtug0.js', ['Gtug.Gtug0'], ['Gtug', 'Gtug.Base', 'goog.Uri.QueryData', 'goog.dom', 'goog.events', 'goog.json', 'goog.net.XhrIo', 'goog.structs.Map', 'goog.ui.Css3ButtonRenderer', 'goog.ui.CustomButton']);
